#!/bin/sh -e
# -e means script will stop at any error
# Remove the .sh extension and make it executable by anyone
## store the arguments given to the script
read prevCommitSHA latestCommitSHA fullbranchName

BRANCH=${fullbranchName##*/}
LOGFILE="/opt/www/meeno/git.deploy.log"
DEPLOYDIR="/opt/www/meeno/"

echo "branch: $BRANCH"
echo "log: $LOGFILE"

##  Record the fact that the push has been received
echo "$(date +"%Y/%m/%d, %T") | Received push request for branch $BRANCH" >> $LOGFILE
echo "$(date +"%Y/%m/%d, %T") | Received push request for branch $BRANCH"

echo "\033[94m---------------------------Deploy Start-------------------------------------\033[0m"


echo "Deploying to $DEPLOYDIR"

rm -rf ${DEPLOYDIR}*
echo " - Deploy dir cleaned up"
echo " - Starting code checkout" 
GIT_WORK_TREE="$DEPLOYDIR" git checkout -f master
echo " - Finished code checkout"

echo " - Starting npm install"
cd "$DEPLOYDIR"
rm -rf node_modules
npm install
echo " - Finished npm install"
echo " - Starting building javascript"
node_modules/.bin/r.js -o build.js
echo " - Finished building javascript"

echo "Restarting server at $( date +"%F %T" )"

RESTART=TRUE
{ # Try stopping server
	systemctl restart meeno && echo "Stopped server at $( date +"%F %T" )"
} || {
 # In case it fails
	RESTART=FALSE
	echo "Impossible to restart server."
}

echo "\033[94m---------------------------Deploy Complete-------------------------------------\033[0m"

if [ $RESTART ]
then
	echo "\033[33m$(date +"%Y/%m/%d, %T")\033[0m | New code deployed successfully"
	echo "\033[33m$(date +"%Y/%m/%d, %T")\033[0m | New code deployed successfully" >> $LOGFILE
else
	echo "\033[33m$(date +"%Y/%m/%d, %T")\033[0m | New code deployed but server did not restart"
	echo "\033[33m$(date +"%Y/%m/%d, %T")\033[0m | New code deployed but server did not restart" >> $LOGFILE
fi