#!/bin/sh -ex
# -e means script will stop at any error
# PRE COMMIT GIT HOOK
# Meant to force cache expiration in production mode
# Remove the .sh extension and make it executable by anyone

echo "============="
echo "Updating timestamp to force cache expiration in production mode..."
FILE="/opt/git/meeno/appSrv.js"
NOW="$(date +"%Y/%m/%d %T")"
sed -i "s|\(:::timestamp:::\)\(.*\)|\1 $NOW ',|g" $FILE
echo "Timestamp below should correspond to current time:"
sed -n -e 's/^.*:::timestamp::: //p' $FILE
echo "============="
